version: '3.8'
services:
  mysql-res:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: secret        # dùng mật khẩu này để login root
      MYSQL_DATABASE: restaurant
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
