# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - restaurantbe

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Cần quyền write để bump version
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Clean up for deployment
        run: |
          mkdir -p deploy-package/dist
          cp -r dist/* deploy-package/dist/
          cp package.json package-lock.json deploy-package/
          cd deploy-package && npm ci --only=production --no-audit

      - name: Zip artifact for deployment (chỉ bao gồm file cần thiết)
        working-directory: deploy-package
        run: zip -r ../release.zip ./*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EC5A5D0CE78F4899B9537C67791173A9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_79071CCE9D9A4670A380035E599B0614 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CCF48A6F22B14CB686583440DF2AFC70 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'restaurantbe'
          slot-name: 'Production'
          package: release.zip

  version-and-release:
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          PACKAGEJSON_DIR: '.'
        with:
          minor-wording: 'feat,feature'
          major-wording: 'BREAKING,major'
          patch-wording: 'fix,patch'
          rc-wording: 'rc,beta,alpha'
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ steps.version-bump.outputs.newTag }}
          name: Release ${{ steps.version-bump.outputs.newTag }}
          generate_release_notes: true
