# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - restaurantbe

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'  # Thêm caching cho npm

      - name: npm install and build
        run: |
          npm ci  # Thay vì npm install
          npm run build --if-present

      - name: Prepare for deployment
        run: |
          mkdir -p deployment
          cp -r dist package.json package-lock.json deployment/
          
          cat > deployment/.env << EOL
          DATABASE_URL=${{ secrets.AZURE_MYSQL_CONNECTIONSTRING }}
          PORT=8080
          NODE_ENV=production
          EOL
          
          cd deployment && npm ci --omit=dev
          cd .. && zip -r release.zip deployment/*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EC5A5D0CE78F4899B9537C67791173A9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_79071CCE9D9A4670A380035E599B0614 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CCF48A6F22B14CB686583440DF2AFC70 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'restaurantbe'
          slot-name: 'Production'
          package: release.zip
          clean: false  # Không cần xóa tất cả file nếu đã chuẩn bị artifact tối ưu
